"""
engine/protocols/nssk.py
========================
Needham-Schroeder Symmetric Key — Replay vulnerable.

Sources: NS 1978, Denning-Sacco 1981.

M1: A→S: A, B, Na
M2: S→A: {Na, B, K_AB, {K_AB,A}K_BS}K_AS
M3: A→B: {K_AB, A}K_BS        ← this ticket is replayable
M4: B→A: {Nb}K_AB
M5: A→B: {Nb}K_AB              (simplified: Nb-1 modelled as same Nb)

Replay: E replays M3 to B after learning old K_AB.
Variable "Na" consistent across I and S roles.
Variable "K_AB" consistent across I, S, R roles.
Variable "Nb" consistent across R and I roles.
"""

from engine.terms import Atom, Concat, Encrypt
from engine.unifier import Variable
from engine.protocol import AuthClaim, Message, ProtocolDef, Role, SecrecyClaim


def make_nssk() -> ProtocolDef:
    K_AS = Atom("K_AS")   # long-term A-S key — NOT public
    K_BS = Atom("K_BS")   # long-term B-S key — NOT public
    A    = Atom("A")
    B    = Atom("B")
    S    = Atom("S")
    Na   = Atom("Na")     # A's nonce
    Nb   = Atom("Nb")     # B's nonce
    K_AB = Atom("K_AB")   # session key generated by S

    initiator = Role("I", steps=[
        # M1: A, B, Na
        Message(send=True, sender="I", receiver="S",
                term=Concat(A, Concat(B, Na)), label="M1"),
        # M2: {Na, B, K_AB, ticket}K_AS
        Message(send=False, sender="S", receiver="I",
                term=Encrypt(
                    Concat(Variable("Na"),
                    Concat(Variable("B_id"),
                    Concat(Variable("K_AB"), Variable("ticket")))),
                    K_AS), label="M2"),
        # M3: forward ticket to B
        Message(send=True, sender="I", receiver="R",
                term=Variable("ticket"), label="M3"),
        # M4: receive {Nb}K_AB
        Message(send=False, sender="R", receiver="I",
                term=Encrypt(Variable("Nb"), Variable("K_AB")), label="M4"),
        # M5: send {Nb}K_AB (simplified — proves knowledge of K_AB)
        Message(send=True, sender="I", receiver="R",
                term=Encrypt(Variable("Nb"), Variable("K_AB")), label="M5"),
    ])

    server = Role("S", steps=[
        # M1: receive A, B, Na
        Message(send=False, sender="I", receiver="S",
                term=Concat(Variable("A_id"),
                     Concat(Variable("B_id"), Variable("Na"))), label="M1"),
        # M2: send {Na, B, K_AB, {K_AB,A}K_BS}K_AS
        Message(send=True, sender="S", receiver="I",
                term=Encrypt(
                    Concat(Variable("Na"),
                    Concat(B,
                    Concat(K_AB, Encrypt(Concat(K_AB, A), K_BS)))),
                    K_AS), label="M2"),
    ])

    responder = Role("R", steps=[
        # M3: receive ticket {K_AB, A}K_BS — THIS is the replayable message
        Message(send=False, sender="I", receiver="R",
                term=Encrypt(Concat(Variable("K_AB"), Variable("A_id")), K_BS),
                label="M3"),
        # M4: send {Nb}K_AB  (Nb is the fixed atom R generates)
        Message(send=True, sender="R", receiver="I",
                term=Encrypt(Nb, Variable("K_AB")), label="M4"),
        # M5: receive {Nb}K_AB — must be exactly Nb
        Message(send=False, sender="I", receiver="R",
                term=Encrypt(Nb, Variable("K_AB")), label="M5"),
    ])

    return ProtocolDef(
        name="NSSK",
        roles=[initiator, server, responder],
        secrecy_claims=[SecrecyClaim(K_AB, "I")],
        auth_claims=[AuthClaim("I", "R")],
        public_values=[A, B, S],   # K_AS, K_BS NOT public
    )
